### ISSUE TITLE
Transect data entry - hide %cloud 

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#108]
@andrewvanbreda 
On the walk data entry page we have %sun and %cloud options. They sum to 100 and autopopulate values - I.e. if sun is entered it calculates cloud, and visa versa. This is unnecessary for spring and confuses some users.

can you hide the %cloud values from the form?

**Comment by andrewvanbreda** [comment]
@DavidRoy Done

**Comment by DavidRoy** [comment]
Thanks Andy

**Comment by DavidRoy** [comment]
@andrewvanbreda could you quick switch this around so that %cloud is the value shown, not sun

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Done. 
% Cloud now shows on SPRING Walk Data Entry instead of % Sun.
Note for some reason the site seems to be painfully slow at the moment.
I have switched on the aggregate JS/CSS option on the Drupal Performance page which should of been on, although I doubt that would make as much difference as needed.

**Comment by andrewvanbreda** [comment]
Closing, as this one was dealt with quite a while ago.
