### ISSUE TITLE
Improvements to Pan-trap data entry

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#72]
Entering pan trap data is time consuming.  Some suggested improvements.

- [x] when first occasion entering pan trap data (e.g. including location etc).  After entering the data (https://pollinator-monitoring.net/enter-pan-trap-results-fixed-square-survey) it would be helpful to return to enter the next pan trap.  Currently the form directs to the results page after submitting the page
- [x] when entering pan trap data for the second and subsequent sampling occasions, the form requires all information to be entered again, including information that is not likely to change (e.g. country, MVS square, pan trap location).  Look at options to improve the efficiency.  Suggested solutions = have a report of location id, location name, pan trap number with link to add new sample.  The form then opens with location id, location name, pan trap number, pan trap spatial reference pre-populated

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Am confused about the first request regarding the redirect after data entry. That was reported quite a while ago, and it was fixed. I just checked, after entering data, it now just stays on the form, there isn't a redirect URL in the configuration. I just double checked it with a test also.
Will look into second issue.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Have had a look at the second one.
Isn't it the padlock icon what you need? (that currently isn't available for the Country/Square).
What if I got the padlock working on the Country/1km square?
Then the control can be locked to the same value for further entries.

**Comment by DavidRoy** [comment]
@andrewvanbreda that's a good idea to start with, thanks.  Will the padlock work the pan trap location that will change with each trap number.  So if the pan trap number is changed, will the spatial location remain locked?

Sorry for the confusion on the first point.  I'd forgotten this has been fixed

**Comment by andrewvanbreda** [comment]
@DavidRoy 
I haven't checked but I assume it will work with drop-downs, I have never really used the padlocks much myself.
The pan trap number and spatial reference don't know anything about each other, the pan trap number is simply a drop-down. So yes the spatial reference will just remain once locked even as the pan trap number is changed (it can of course be unlocked as needed).
Not sure how tricky it will be to get working on the Country/Square linked drop-downs, could either be super easy or trickier.

**Comment by DavidRoy** [comment]
@andrewvanbreda 
Ok, in that case I think we need pad-locks on the country and MVS 1km site but not the pan trap spatial reference.  This will help the initial setup of the pan trap locations.

Therefore, for the requirement to enter the pan trap samples from visit 2 onwards does it makes sense to have a report of location id, location name, pan trap number with a link to add new sample. The form then opens with location id, location name, pan trap number, pan trap spatial reference pre-populated?

**Comment by andrewvanbreda** [comment]
@DavidRoy That is a possibility. I need to think about how to get it to work as the data needs storing against the location to report on.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
I have added padlocking with the country/square, and that is live.
I had to add some custom code to get these to work together.
This includes code that auto-changes the padlock state of the country when the user changes the padlock on the square.

I noticed above, you had some interest as to whether the locking on the pan trap number and spatial reference were linked together.
The answer to this is they aren't, however they could be.
So for instance, unlocking the pan trap number could auto-unlock the spatial reference (locking could lock the same field).

In your ideal world, how would you envision all the locks working?
As I think we can (probably) make it happen.

**Comment by andrewvanbreda** [comment]
@andrewvanbreda
Not to myself. Also add padlocking as per this volunteers request
"Similarly, either the primary or secondary habitat of each pantra should be kept the same through all the surveys:"

**Comment by andrewvanbreda** [comment]
Locks added to Primary and Secondary Habitat fields as per volunteer request.

**Comment by iverkaik** [comment]
Hello,
I don't know if i am doing it correctly but yesterday i entered the data for a second survey and all the pan traps locations have to be re-entered again. Would be possible to fix the pan traps location (after the first time such as the transects) and just enter the other data? it is really time consuming. Or maybe I did it not properly?

thank you,
iraima

**Comment by andrewvanbreda** [comment]
Hello iraima @iverkaik,

I have just tried testing the system, and have noticed an issue I did not notice before.

What should happen is that if you click the padlock next to the "1km square" field, and also the lock next to the "Trap grid reference", these are remembered next time you go to the page.
This is working.
However, I had not noticed the map is not reacting to these locks and is remaining zoomed out.

I will look into correcting this and let you know.

Thank you for your feedback.

Andy

**Comment by iverkaik** [comment]
Hello Andy,

Thank you for your quick reaction.
I hope this can get fixed as it will ease a lot the data entrance for the pantraps.

thank you!
iraima

**Comment by andrewvanbreda** [comment]
Hello iraima @iverkaik,

There is now a fix that is live that zooms the map when the square is locked. I hope that makes things easier.
As I did this quickly, I have a couple of other improvements I would like to do, but I hope that helps.

Andy

**Comment by iverkaik** [comment]
Hello Andy,

I understood finally today what you ment about the square is locked! that is good for a part.
The problem is when you have to enter each data pan trap data becasue each is located in different locations, so this should not be locked. My idea was to be able to just add the results once you select the pan trap and not to have to enter the location again. I get you have to enter this the first time but for the second survey (other data) the pan trap should be at the same location. And then it makes sense, to add if the pan trap was moved.
Hope I could explain the situation.
Thank you,
Iraima

**Comment by andrewvanbreda** [comment]
Hi @iverkaik

I will have a look tomorrow at what you are saying there, and get back to you.

Andy

**Comment by andrewvanbreda** [comment]
Hi iraima @iverkaik ,

I think I get what you mean, that once you select the Country, Square then the Pan Trap Number, then the grid reference would be the same and therefore should default to the grid reference previously entered.

I have to say I am trying to think of a way to achieve this but am struggling because of the way the system works.

It might be possible to get it so that when you select the pan-trap, the computer could try and look up previously surveys and get the grid reference from there.
Not quite sure how slow that might be though.

Leave it with me, but I don't think I will be able to fix this in the very short term though.

Andy

**Comment by andrewvanbreda** [comment]
@iverkaik 
Actually I have an idea. 
If I add an extra icon column to the My Fixed Square Results page that allows you to add a new entry with the previous survey as a kind of partially pre-filled template, that might work.
Effectively a "use previous survey values" button.
Again not quite sure how quickly I will be able to get something like that onto the system, but will try as soon as able.
Possibly implement my other suggestion also depending on if the computer can do that quickly enough.

**Comment by iverkaik** [comment]
Hello, Andy,

Thank you for your quick reactions and ideas. The last one sounds good to me, thank you!!!

**Comment by andrewvanbreda** [comment]
Hi @iverkaik 
I have finished coded, tested and committed the change for adding a pan trap sample based on an existing one.
This will get double-checked by someone else before an official release, so there will be a delay before actually gets on the SPRING system.
It should be available soon in the new year, but let me know if you really need it before then.

**Comment by iverkaik** [comment]
Hi Andy,
This is great news! It will be OK to have it next year. I asked the volunteers to work on the transsect set-up and results upload and be patient for the pantraps. So the timing is perfect.
Thank you very much and happy holidays,
Iraima

________________________________
De: andrewvanbreda ***@***.***>
Enviado: viernes, 23 de diciembre de 2022 14:25
Para: BiologicalRecordsCentre/SPRING ***@***.***>
Cc: Iraima Verkaik ***@***.***>; Mention ***@***.***>
Asunto: Re: [BiologicalRecordsCentre/SPRING] Improvements to Pan-trap data entry (Issue #72)


Hi @iverkaik<https://github.com/iverkaik>
I have finished coded, tested and committed the change for adding a pan trap sample based on an existing one.
This will get double-checked by someone else before an official release, so there will be a delay before actually gets on the SPRING system.
Itshould be available soon in the new year, but let me know if you really need it before then.

**Comment by iverkaik** [comment]
Hi Andy,

I just try to enter the data but I am guessing the "new" system is not ready jet. Any ideas when will this be ready?

Thank you!
Iraima

**Comment by andrewvanbreda** [comment]
Hi @iverkaik,
The code is done however it isn't live yet.
What happens is that I complete the code, then it gets committed into our general development code for double-checking by another programmer.
I don't really have control of the speed that happens as I am not the one doing it.

What I will do is ask around about how soon it might get checked, and if it isn't soon, I will find out about deploying it quickly and safely.
I will do that right now and let you know.

**Comment by andrewvanbreda** [comment]
I have now asked about this, awaiting response

**Comment by iverkaik** [comment]
Thank you @andrewvanbreda!

**Comment by andrewvanbreda** [comment]
Hi @iverkaik,
I have heard back saying end of next week, is that ok?

**Comment by iverkaik** [comment]
yes, that is OK! thank you!

**Comment by andrewvanbreda** [comment]
Hi @iverkaik @DavidRoy 
This is now live.
Access from the "Use as template for a new survey" link found to the right of each row on the "My fixed square results" page.
Note we can vary which fields are copied across if the ones I have chosen are not suitable.
Currently fields that are copied are:
Country, Square, Grid Reference, Pan Trap Number.

**Comment by iverkaik** [comment]
Hi @andrewvanbreda ,

I finally got the time to try the new method to ease the pan trap data entrance.
And I am really sorry to say this, but I do not think this is very helpful for some of the following reasons:
- It is not intuitive and in my screen I cannot see which pantrap it is:
![Captura de pantalla 2023-02-14 162951](https://user-images.githubusercontent.com/120505944/218786062-221e8387-c411-4d9a-9eec-356ae6b2bb91.png)

- The entrance needs be still done pan trap by pan trap. And each time you need to go back to your results to enter the results. With this, it will still be better to enter each time the UTM of the pantrap.
- Again, my "idea" is to link directly each time you choose the pantrap that could be related to the one you have already entered. Here instead of the "centre" of the site, why do not add the pantrap location?
![image](https://user-images.githubusercontent.com/120505944/218786697-abe09af1-b8a0-43b9-85c1-d59e7bae8b04.png)
- Another option could be to do a previous excercise such as "step-up" the pantraps like the transsects. And you may add the results such as the transect walks. Could that be a possibility?

Perhpas it is too complicated but this new option I do not think this will help to ease data entrance. I hope I am wrong. Let's see what are the other users experience.

thank you,
iraima

**Comment by andrewvanbreda** [comment]
Hi @iverkaik @DavidRoy,

I am sorry this change hasn't been useful.

In response to your points:

1. 
The pan-trap number is not visible on the grid because there are so many columns.

David:
Should we reduce the number of columns in the grid? (but have the full set in the download file)?
or
I could add a third grid purely for the "Use as a template for a new survey" functionality with minimal columns.

2.
I think the issue with your second point is that another Github issue near the start of the project requested that the form should always return to itself.
David: Should we change the screen to return to the My Results grid?

3. 
The data entry page is based on the one that was designed for the UKPoMS project.
The pan-trap drop-down is a simple list of words, which actually have no structure/logic associated with them. The list does not even know that it is related to anything else on the page. It is literally just a list of numbers.
Given this, it would very difficult to do as you request.
I guess I could detect when a user selects a number, then look up the existing samples and reload the page with the exist data.
However I wonder if the effect would actually be similar to if I made the improvements suggested in points 1 or 2 anyway. I think I will need David to comment.

4.
In regards to making the page similar to a transect walk. Note again the notes made in point 3 about the list being a simple list.
It was take a complete page redesign to implement something like transect walks.
I guess it would be down to David if he wanted to move the project in that direction.

**Comment by iverkaik** [comment]
Hi @andrewvanbreda 

Thank you for your quick answer. I understand that this has been adapted from the UKPoMS and may have different objectives and challenges. I was just thinking the way to ease the data entrance to volunteers (and myself as some of them already gave up!).
I am sorry to be repetitive but here is the list of the data that does not change -unless something happened-:
- The pantrap location and number
- The primary and secondary habitat of the pantrap
- The flower type once one of the species list has been selected

The other buttons to "lock" and "unlock" are very helpful for the data, the country, square, recorder, data. But this does not work for the tap grid reference as each pantrap is located in different points and not on the centre of the square.

Many thanks and sorry to keep asking,
iraima

**Comment by andrewvanbreda** [comment]
Hi @iverkaik @DavidRoy 

Yes, this essentially the same thing I am trying to do also. 
I would love to implement every request, but in reality I am just a programmer who simply programs the functionality I am asked to by the design teams. There are also other constraints such as Github issues that might clash, or requests that are not technically feasible within budget.

Although I am not in charge of system design, if there are people being put-off using the current system, I think it is in the interests of the project to make changes as soon as I can. I normally wouldn't do that without David approving first, but I am going to assume I am not making the situation worse.
@DavidRoy can ask me to undo changes if needed.

With that in mind I have tried to make as many changes as I can, given the limitations I am faced with.
These are now done and are as follows:

1. Instructions added to the My Fixed Square Results screen.

2. A new grid added with far fewer columns. This allows you to see important columns for the existing sample you are using as a template (such as pan trap number)

3. My Fixed Square Results is split into 3 tabs. The new grid is on the first tab.

4. A new button added below each grid to take you straight to the data entry page.

5. The data entry page now returns to the My Fixed Squares page, so that a new entry can be made either by adding new data (using the new buttons), editing existing, or using the template functionality.

6. Primary and Secondary Habitat are now added to the fields that are retained when using the "Use as template for new survey" functionality.

I am unable to implement the 
"The flower type once one of the species list has been selected" functionality at the moment. Although I do understand the requirement, I do not currently have a way to get that to work, it is a very different requirement to retaining the sample fields.

The location should already be copied, if you think there is a problem with that can you let me know, it seems to work for me.

I hope that helps.
If it does not, or you feel it still it is not enough, we may need to talk to David about the possibility of redesigning cetain areas.

**Comment by iverkaik** [comment]
Hi @andrewvanbreda ,

Wow! thank you for all these changes. 
I just tried quikcly some of them and they are very useful, thank you!

I will keep you updated if I get feedback from other volunteers. 

Thank you very much,
iraima

**Comment by DavidRoy** [comment]
Closing for now.  Any further suggestions as new issues
