### ISSUE TITLE
Unable to enter end-time and temperature on transect entry page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#74]
Unable to select two sample attribute fields: end-time and temperature
https://pollinator-monitoring.net/walk-data-entry?location_type_id=777&date=19/07/2022

**Comment by andrewvanbreda** [comment]
@DavidRoy 
The problem was not what I thought it might be.

The problem was with the CSS that is used to layout the form.
I have removed the troublesome part and take the site out of maintenance mode..
This does mean the layout of the page may be a little erratic for now.
But this afternoon I will try to fix the CSS using the test site.

To be fair to Biren, I have no idea why the CSS that is causing the trouble would do so.
It doesn't even directly affect the field that has the problems.
There is no way he could of written that CSS, and foreseen this kind of issue, it is almost like it is being misinterpreted.

**Comment by andrewvanbreda** [comment]
Please leave this issue open until proper fix implemented.

**Comment by DavidRoy** [comment]
UK PoMS and https://butterfly-monitoring.net/ use the same broad theme and CSS so it's odd that only this site is problematic?

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
The reason for this is that it is not the theme that is causing the issue.
It is the CSS that was added to align the 2 columns of attributes.
That was added to a CSS file specific to the page (you can think of it as theme override).
I think the problem would of started the other day when further changes were made to the layout here
https://github.com/BiologicalRecordsCentre/SPRING/issues/52

**Comment by andrewvanbreda** [comment]
@DavidRoy 
I have made adjustments to the format of the page. The original problem with the fields fixed.
Closing
